model:
  name: spvcnn18

dataset:
  name: s3dis
  root: /rscratch/data/s3dis/Stanford3dDataset_v1.2_Aligned_Version
  voxel_size: 0.05
  num_classes: 14

data:
  ignore_label: 10
  input_dim: 6
  less_frame: 0.1
  clip_bound: 4
  color_std: 0.005
  color_trans_ratio: 0.05

train:
  seed: 1588147245
  trainable_params: all
  pretrained: False

criterion:
  name: cross_entropy
  ignore_index: 255

optimizer:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  nesterov: true

scheduler:
  name: polyLR
  max_iter: 10400
  power: 0.9

num_epochs: 400
batch_size: 3
