model:
  name: spvcnn34_cls

dataset:
  name: modelnet
  root: /rscratch/data/modelnet/modelnet40_ply_hdf5_2048
  voxel_size: 0.05
  num_classes: 40

data:
  num_points: 2048
  ignore_label: -1
  input_dim: 3
  distill_path: /rscratch/shijiayang/PC_dataeff/34_scratch_5shot

train:
  seed: 777
  transformation: z-axis
  
criterion:
  name: soft_pseudolabel_with_temperature
  ignore_index: 255
  temperature: 0.8

optimizer:
  name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-04
  nesterov: False

scheduler:
  name: cosine

num_epochs: 300
batch_size: 32
